# Generated by Django 3.2.4 on 2021-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuTimer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'menu_timer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuToStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'menu_to_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderTimer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'order_timer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.CharField(blank=True, max_length=10, null=True)),
                ('staff_pw', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tables',
                'managed': False,
            },
        ),
    ]
